package com.francis.voxchat.chat;

import com.francis.voxchat.VoxChatMod;
import net.minecraft.client.MinecraftClient;
import net.minecraft.client.gui.screen.ChatScreen;

/**
 * Injects recognised speech text into the Minecraft chat input box.
 *
 * Rules:
 *  - NEVER auto-sends — the player must press Enter.
 *  - If the chat screen is already open, text is appended to whatever is there.
 *  - If the chat screen is not open, it is opened with the text pre-filled.
 *  - Must be called on the Minecraft client thread.
 */
public final class ChatInjector {

    private ChatInjector() {}   // utility class

    /**
     * Inserts {@code text} into the chat input field.
     *
     * <p>Must be called on the Minecraft client (render) thread.
     * Use {@code client.execute(() -> ChatInjector.injectText(client, text))}
     * when calling from a background thread.</p>
     *
     * @param client the active {@link MinecraftClient}
     * @param text   the recognised text to insert (not null, not blank)
     */
    public static void injectText(MinecraftClient client, String text) {
        if (text == null || text.isBlank()) {
            VoxChatMod.LOGGER.debug("[VoxChat] ChatInjector: nothing to inject.");
            return;
        }

        // Sanitise — strip newlines to avoid accidental send
        String sanitised = text.replace('\n', ' ').replace('\r', ' ').trim();

        if (client.currentScreen instanceof ChatScreen chatScreen) {
            // Chat is already open — append text to whatever the player typed
            appendToChatScreen(chatScreen, sanitised);
        } else {
            // Open the chat screen pre-seeded with our text
            openChatWithText(client, sanitised);
        }
    }

    // -------------------------------------------------------------------------
    // Internal helpers
    // -------------------------------------------------------------------------

    /**
     * Appends {@code text} to the existing content of an already-open
     * {@link ChatScreen} by accessing its chat input field via the
     * accessible accessor mixin generated by Fabric.
     *
     * If the accessor is unavailable we fall back to closing and reopening.
     */
    private static void appendToChatScreen(ChatScreen chatScreen, String text) {
        try {
            // ChatScreen exposes the chat field via net.minecraft.client.gui.widget.TextFieldWidget
            // We use reflection here so we do not need a mixin just for this simple field.
            var fieldClass = chatScreen.getClass();

            // Walk up the class hierarchy looking for the "chatField" field.
            // In Yarn 1.21.1 mappings it is named 'chatField' on ChatScreen.
            java.lang.reflect.Field chatField = findField(fieldClass, "chatField");
            if (chatField == null) {
                // Fallback: close and reopen — the existing chat content is lost but
                // the player gets the recognised text.
                VoxChatMod.LOGGER.debug("[VoxChat] chatField not found via reflection, falling back to reopen.");
                String currentText = extractCurrentText(chatScreen);
                String combined   = currentText.isEmpty() ? text : currentText + " " + text;
                openChatWithText(chatField(chatScreen), combined);
                return;
            }

            chatField.setAccessible(true);
            Object textField = chatField.get(chatScreen);

            // TextFieldWidget inherits from net.minecraft.client.gui.widget.TextFieldWidget
            // It has a `write(String)` method in Yarn mappings.
            java.lang.reflect.Method writeMethod = findMethod(textField.getClass(), "write", String.class);
            if (writeMethod != null) {
                writeMethod.setAccessible(true);
                // Ensure there's a trailing space before appended text
                String current = extractCurrentText(chatScreen);
                if (!current.isEmpty() && !current.endsWith(" ")) {
                    writeMethod.invoke(textField, " " + text);
                } else {
                    writeMethod.invoke(textField, text);
                }
                VoxChatMod.LOGGER.debug("[VoxChat] Appended to open chat: \"{}\"", text);
            } else {
                VoxChatMod.LOGGER.warn("[VoxChat] TextFieldWidget.write() not found; reopening chat.");
                String combined = extractCurrentText(chatScreen);
                openChatWithText(chatField(chatScreen), combined.isEmpty() ? text : combined + " " + text);
            }

        } catch (Exception e) {
            VoxChatMod.LOGGER.error("[VoxChat] Reflection error in appendToChatScreen: {}", e.getMessage(), e);
        }
    }

    /** Opens a fresh {@link ChatScreen} with the given pre-filled text. */
    private static void openChatWithText(MinecraftClient client, String text) {
        // ChatScreen(String defaultText) — sets the initial content
        client.setScreen(new ChatScreen(text));
        VoxChatMod.LOGGER.debug("[VoxChat] Chat opened with text: \"{}\"", text);
    }

    /** Overload that accepts a ChatScreen to retrieve its client reference. */
    private static void openChatWithText(ChatScreen screen, String text) {
        // ChatScreen extends Screen which has a `client` field
        try {
            java.lang.reflect.Field clientField = findField(screen.getClass(), "client");
            if (clientField != null) {
                clientField.setAccessible(true);
                MinecraftClient mc = (MinecraftClient) clientField.get(screen);
                openChatWithText(mc, text);
                return;
            }
        } catch (Exception ignored) {}
        // If we still can't find the client, try the singleton
        openChatWithText(MinecraftClient.getInstance(), text);
    }

    /** Returns the client from a ChatScreen (needed in some code paths). */
    private static MinecraftClient chatField(ChatScreen screen) {
        return MinecraftClient.getInstance();
    }

    /**
     * Attempts to read the current text from the chat screen's input field.
     * Returns an empty string on failure.
     */
    private static String extractCurrentText(ChatScreen chatScreen) {
        try {
            java.lang.reflect.Field chatField = findField(chatScreen.getClass(), "chatField");
            if (chatField == null) return "";
            chatField.setAccessible(true);
            Object textField = chatField.get(chatScreen);

            // getText() / text getter
            java.lang.reflect.Method getText = findMethod(textField.getClass(), "getText");
            if (getText == null) return "";
            getText.setAccessible(true);
            Object result = getText.invoke(textField);
            return result == null ? "" : result.toString();
        } catch (Exception e) {
            return "";
        }
    }

    // -------------------------------------------------------------------------
    // Reflection utilities
    // -------------------------------------------------------------------------

    /** Searches {@code cls} and all its superclasses for a field with the given name. */
    private static java.lang.reflect.Field findField(Class<?> cls, String name) {
        while (cls != null) {
            for (java.lang.reflect.Field f : cls.getDeclaredFields()) {
                if (f.getName().equals(name)) return f;
            }
            cls = cls.getSuperclass();
        }
        return null;
    }

    /** Searches {@code cls} and all its superclasses for a method with the given name and parameter types. */
    private static java.lang.reflect.Method findMethod(Class<?> cls, String name, Class<?>... params) {
        while (cls != null) {
            try {
                return cls.getDeclaredMethod(name, params);
            } catch (NoSuchMethodException ignored) {}
            cls = cls.getSuperclass();
        }
        return null;
    }
}
